-- ============================================================================
-- V0x3l-managed Hyprland config (Lua) — DO NOT EDIT (se sobreescribe en re-runs)
-- Based on DMS template + V0x3l customizations.
-- DMS provee barra, lanzador, terminal y notificaciones.
-- ============================================================================

hl.config({ autogenerated = false })

-- ── Environment variables ──────────────────────────────────────────────────
-- Qt: obligatorias para DMS (Quickshell/Qt). Sin QT_QPA_PLATFORM=wayland,
-- Qt intenta usar xcb y falla con "could not load platform plugin xcb".
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

-- ── NVIDIA runtime detection ───────────────────────────────────────────────
-- Detecta si el driver NVIDIA esta cargado y setea las env vars necesarias.
-- En sistemas AMD/Intel es no-op (el archivo no existe).
local nvidia_file = io.open("/proc/driver/nvidia/version")
if nvidia_file then
	nvidia_file:close()
	hl.env("LIBVA_DRIVER_NAME", "nvidia")
	hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
	hl.env("NVD_BACKEND", "direct")
	hl.env("GBM_BACKEND", "nvidia-drm")
end

-- ── DMS startup (exec-once equivalente) ────────────────────────────────────
-- dbus-update: necesario para XDG Desktop Portal y servicios systemd.
-- dms run: lanza DMS directamente. La doc de DMS (Managing) dice que Hyprland
-- no tiene systemd session targets nativos -> usar exec-once = dms run.
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("dms run")
end)

-- ── Monitors ───────────────────────────────────────────────────────────────
hl.monitor({
	output   = "",
	mode     = "preferred",
	position = "auto",
	scale    = 1.0,
})

-- ── Input / Layout / Decoration ────────────────────────────────────────────
hl.config({
	input = {
		kb_layout = "latam",
		numlock_by_default = true,
		follow_mouse = 1,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

-- ── Animations ─────────────────────────────────────────────────────────────
hl.animation({ leaf = "windowsIn",  enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove",enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade",       enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border",     enabled = true, speed = 3, bezier = "default" })

-- ── Window rules ───────────────────────────────────────────────────────────
hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
-- PiP: Firefox y Floorp (Floorp es fork de Firefox, class distinta)
hl.window_rule({ match = { class = "^(firefox)$",  title = "^(Picture-in-Picture)$" }, float = true })
hl.window_rule({ match = { class = "^(floorp)$",   title = "^(Picture-in-Picture)$" }, float = true })
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
-- DMS / Quickshell layers
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

-- ── DMS config modules ─────────────────────────────────────────────────────
-- Creados por 'dms setup binds/colors/layout/...' (Step 5 de V0x3l).
-- Si no existen aun (Step 5 no corrio), Hyprland los salta sin crashear.
require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
