-- DMS colors (Material You) — auto-generated by DMS theme tools.
-- V0x3l pre-stage: copiado desde el template de DMS.

hl.config({
	general = {
		col = {
			active_border = "rgb(d0bcff)",
			inactive_border = "rgb(948f99)",
		},
	},
	group = {
		col = {
			border_active = "rgb(d0bcff)",
			border_inactive = "rgb(948f99)",
			border_locked_active = "rgb(f2b8b5)",
			border_locked_inactive = "rgb(948f99)",
		},
		groupbar = {
			col = {
				active = "rgb(d0bcff)",
				inactive = "rgb(948f99)",
				locked_active = "rgb(f2b8b5)",
				locked_inactive = "rgb(948f99)",
			},
		},
	},
})
