-- DMS layout (gaps, borders, rounding) — auto-generated by DMS.
-- V0x3l pre-stage: copiado desde el template de DMS.

hl.config({
	general = {
		gaps_in = 4,
		gaps_out = 4,
		border_size = 2,
	},
	decoration = {
		rounding = 12,
	},
})
